# Generated by Django 3.2 on 2021-04-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0002_auto_20210424_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='to_hour',
        ),
    ]
