# Generated by Django 3.2 on 2021-04-24 18:06

import apps.cources.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0003_remove_worktime_to_hour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktime',
            options={'verbose_name': 'Рабочие дни', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AlterField(
            model_name='worktime',
            name='from_hour',
            field=models.TimeField(validators=[apps.cources.service.validate_round_hour]),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], unique=True),
        ),
    ]
