# Generated by Django 3.2 on 2021-04-24 18:38

import apps.cources.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0004_auto_20210424_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='from_hour',
        ),
        migrations.AddField(
            model_name='courses',
            name='from_hour',
            field=models.TimeField(default='00:00', validators=[apps.cources.service.validate_round_hour]),
        ),
    ]
