# Generated by Django 3.2 on 2021-04-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0005_auto_20210424_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='from_hour',
        ),
    ]
