# Generated by Django 3.2 on 2021-04-24 19:16

import apps.cources.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0006_remove_courses_from_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.TimeField(default='00:00', validators=[apps.cources.service.validate_round_hour])),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='students_hour',
            field=models.ManyToManyField(related_name='cource', to='cources.StudentHour'),
        ),
    ]
