# Generated by Django 3.2 on 2021-04-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0007_auto_20210424_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='students_hour',
        ),
        migrations.DeleteModel(
            name='StudentHour',
        ),
    ]
