# Generated by Django 3.2 on 2021-04-25 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0008_auto_20210424_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='weekday',
        ),
        migrations.AddField(
            model_name='worktime',
            name='date_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
