# Generated by Django 3.2 on 2021-04-25 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0009_auto_20210425_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='date_time',
            field=models.DateField(default=datetime.datetime.now, unique_for_date=True),
        ),
    ]
