# Generated by Django 3.2 on 2021-04-25 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0010_alter_worktime_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='date_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
