# Generated by Django 3.2 on 2021-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='work_time',
        ),
        migrations.AlterField(
            model_name='studenthour',
            name='cource_work_time',
            field=models.ManyToManyField(null=True, related_name='hour', to='cources.WorkTime'),
        ),
    ]
