# Generated by Django 3.2 on 2021-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0002_auto_20210424_1759'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkTime',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_time',
            field=models.ManyToManyField(to='cources.WorkTime'),
        ),
    ]
