# Generated by Django 3.2 on 2021-04-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_from_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='from_hour',
        ),
    ]
