# Generated by Django 3.2 on 2021-04-24 19:25

import apps.cources.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0008_auto_20210424_1925'),
        ('users', '0006_remove_student_from_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cources',
        ),
        migrations.CreateModel(
            name='StudentHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.TimeField(default='00:00', validators=[apps.cources.service.validate_round_hour])),
                ('cource', models.ManyToManyField(related_name='hour', to='cources.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='students_hour',
            field=models.ManyToManyField(related_name='student', to='users.StudentHour'),
        ),
    ]
