# Generated by Django 3.2 on 2021-04-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210424_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='students_hour',
            new_name='cource',
        ),
    ]
