# Generated by Django 3.2 on 2021-04-24 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0008_auto_20210424_1925'),
        ('users', '0008_rename_students_hour_student_cource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthour',
            name='cource',
        ),
        migrations.AddField(
            model_name='studenthour',
            name='cource',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hour', to='cources.courses'),
        ),
    ]
