# Generated by Django 3.2 on 2021-04-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0008_auto_20210424_1925'),
        ('users', '0009_auto_20210424_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], unique=True)),
            ],
            options={
                'verbose_name': 'Рабочие дни',
                'verbose_name_plural': 'Рабочие дни',
            },
        ),
        migrations.AlterField(
            model_name='studenthour',
            name='from_hour',
            field=models.TimeField(choices=[('00:00:00', 'Midnight'), ('01:00:00', '01 AM'), ('02:00:00', '02 AM'), ('03:00:00', '03 AM'), ('04:00:00', '04 AM'), ('05:00:00', '05 AM'), ('06:00:00', '06 AM'), ('07:00:00', '07 AM'), ('08:00:00', '08 AM'), ('09:00:00', '09 AM'), ('10:00:00', '10 AM'), ('11:00:00', '11 AM'), ('12:00:00', 'Noon'), ('13:00:00', '01 PM'), ('14:00:00', '02 PM'), ('15:00:00', '03 PM'), ('16:00:00', '04 PM'), ('17:00:00', '05 PM'), ('18:00:00', '06 PM'), ('19:00:00', '07 PM'), ('20:00:00', '08 PM'), ('21:00:00', '09 PM'), ('22:00:00', '10 PM'), ('23:00:00', '11 PM')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='cources',
            field=models.ManyToManyField(related_name='teacher', to='cources.Courses'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_time',
            field=models.ManyToManyField(to='users.TeacherWorkTime'),
        ),
    ]
