# Generated by Django 3.2 on 2021-04-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210424_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthour',
            options={'verbose_name': 'Часы', 'verbose_name_plural': 'Часы'},
        ),
    ]
