# Generated by Django 3.2 on 2021-04-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_studenthour_from_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthour',
            name='from_hour',
            field=models.TimeField(default='0:00'),
        ),
    ]
