# Generated by Django 3.2 on 2021-04-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_studenthour_cource_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='test_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='wotk_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
