# Generated by Django 3.2 on 2021-04-25 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210425_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherworktime',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 8, 45, 39, 183741)),
        ),
    ]
