# Generated by Django 3.2 on 2021-04-25 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_teacherworktime_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherworktime',
            name='date_time',
            field=models.DateField(default=datetime.datetime.now, unique_for_date=True),
        ),
    ]
