# Generated by Django 3.2 on 2021-04-25 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cources', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start', models.TimeField()),
                ('finish', models.TimeField()),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.courses')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
            options={
                'verbose_name': 'Образовательный центр',
                'verbose_name_plural': 'Образовательный центр',
            },
        ),
    ]
