# Generated by Django 3.2 on 2021-04-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cources', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Education',
        ),
    ]
